### ISSUE TITLE
Mobility Print out of Date

### ISSUE THREAD

**Issue by roofuskit** [snorre-k/mobility-print#1]
Cannot connect to Cloud Print because the mobility print software is out of date.

2023/10/27 22:19:38 mobility-print: STDOUT|DEV: request failed [ Request=POST https://mp.cloud.papercut.com/server/v1/register status=400 Bad Request error=Registration denied. Broker URL support must be specified in registration request.Upgrade to the latest Mobility Print Server. ] {"src":"restclient.go:166"}

**Comment by snorre-k** [comment]
Sorry for the inconvenience. The build workflow was disabled automatically as I did not do any changes to the repository. I have again enabled the pipeline and now a fresh container with the up-to-date Papercut Mobility Print can be pulled.
